# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python-version }}, OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.5", "3.7.5", "3.10"]
        os: [ubuntu-latest, ubuntu-18.04, macos-latest]
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pytahon-version }}
    - name: Install using pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    # Install pandoc for building docs
    - name: Install pandoc for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install pandoc
    - name: Install pandoc for Windows
      if: matrix.os == 'windows-latest'
      run: choco install pandoc --no-progress
    - name: Install pandoc for MacOS
      if: matrix.os == 'macos-latest'
      run: brew install pandoc
    - name: Test with pytest
      run: |
        cd docs
        make html
