name: pip-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Testing pip install, updating requirements.txt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.5", "3.7.5", "3.10"]
        os: [ubuntu-latest, ubuntu-18.04, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install using pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Test on pytest
      run:
        pytest
